import {
    ShieldAlert,
  Clock,
  MapPin,
  Headphones,
  Star,
  Users,
} from "lucide-react";

export const VALUES = [
  {
    icon: ShieldAlert,
    title: "Transparent Pricing",
    body: "No hidden charges, no last-minute surprises. Every rupee is accounted for before you pack your bags.",
    stat: "100%",
    statLabel: "Price Clarity",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
    alt: "Mountain landscape representing transparent travel pricing",
  },
  {
    icon: Clock,
    title: "On-Time Operations",
    body: "Precision logistics across every destination — from hotel check-ins to Himalayan transfers.",
    stat: "98%",
    statLabel: "On-Time Rate",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80",
    alt: "Himalayan trail representing reliable travel operations",
  },
  {
    icon: MapPin,
    title: "Local Expertise",
    body: "Born in Shimla, built for the mountains. Our ground knowledge converts into seamless experiences.",
    stat: "5+",
    statLabel: "Years On Ground",
    image: "https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=600&q=80",
    alt: "Shimla hill station representing local travel expertise",
  },
  {
    icon: Headphones,
    title: "24/7 Support",
    body: "A real person answers when you call — during your trip, not just while booking.",
    stat: "24/7",
    statLabel: "Live Assistance",
    image: "https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=600&q=80",
    alt: "Beautiful destination representing round the clock travel support",
  },
  {
    icon: Star,
    title: "Curated Stays",
    body: "Every hotel and homestay is personally verified. Comfort and character — never a coin toss.",
    stat: "200+",
    statLabel: "Verified Properties",
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&q=80",
    alt: "Premium hotel room representing curated accommodation selection",
  },
  {
    icon: Users,
    title: "Group & Family First",
    body: "Designed for India's diverse travellers — families, couples, pilgrimages, and corporate groups.",
    stat: "5000+",
    statLabel: "Happy Travellers",
    image: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600&q=80",
    alt: "Group of happy travellers representing family and group tours",
  },
];