import {
  WifiIcon,
  TruckIcon,
  BuildingStorefrontIcon,
  BoltIcon,
  SparklesIcon,
  FireIcon,
  ClockIcon,
  TvIcon,
  PhoneIcon,
  ShieldCheckIcon,
  VideoCameraIcon,
  BellAlertIcon,
  HeartIcon,
  BeakerIcon,
  SunIcon,
  MoonIcon,
  KeyIcon,
  BriefcaseIcon,
  PrinterIcon,
  BanknotesIcon,
  UserGroupIcon,
  CakeIcon,
  ArrowsUpDownIcon,
  HomeModernIcon,
  PuzzlePieceIcon,
  MusicalNoteIcon,
  BookOpenIcon,
  GlobeAltIcon,
  ArchiveBoxIcon,
  Battery50Icon,
  ComputerDesktopIcon,
  DevicePhoneMobileIcon,
  LifebuoyIcon,
  ScissorsIcon,
  Squares2X2Icon,
  SwatchIcon,
  WrenchScrewdriverIcon,
} from "@heroicons/react/24/outline";

// Shared between the hotel detail page's compact amenity preview and the
// full "View All" amenities modal, keyed by the same icon slug booking-data's
// iconFor() assigns server-side.
//
// Kept broad on purpose: the imported catalogue carries 111 distinct amenity
// values, and with only a handful of slugs almost every row in the modal fell
// back to the same generic glyph — a wall of identical icons reads as
// placeholder content even when the underlying data is real.
export const AMENITY_ICONS: Record<string, typeof WifiIcon> = {
  wifi: WifiIcon,
  parking: TruckIcon,
  restaurant: BuildingStorefrontIcon,
  ac: BoltIcon,
  pool: SparklesIcon,
  gym: FireIcon,
  spa: SparklesIcon,
  desk: ClockIcon,

  tv: TvIcon,
  phone: PhoneIcon,
  security: ShieldCheckIcon,
  cctv: VideoCameraIcon,
  alarm: BellAlertIcon,
  medical: HeartIcon,
  toiletries: BeakerIcon,
  water: LifebuoyIcon,
  heating: SunIcon,
  bedding: MoonIcon,
  safe: KeyIcon,
  business: BriefcaseIcon,
  printer: PrinterIcon,
  payment: BanknotesIcon,
  reception: UserGroupIcon,
  kitchen: CakeIcon,
  elevator: ArrowsUpDownIcon,
  balcony: HomeModernIcon,
  games: PuzzlePieceIcon,
  music: MusicalNoteIcon,
  library: BookOpenIcon,
  transfer: GlobeAltIcon,
  storage: ArchiveBoxIcon,
  power: Battery50Icon,
  workspace: ComputerDesktopIcon,
  device: DevicePhoneMobileIcon,
  grooming: ScissorsIcon,
  furniture: Squares2X2Icon,
  laundry: SwatchIcon,
  service: WrenchScrewdriverIcon,
};
