export const FAQS = [
  // Booking & Payments
  { id: 1, cat: "booking", q: "How do I book a trip with Dreams Yatri?", a: "You can book by filling out the enquiry form on our website, calling us directly at +91 70239 07023, or emailing us at sales@dreamsyatri.com. Our team will get back to you within a few hours to discuss your requirements and share a customised itinerary." },
  { id: 2, cat: "booking", q: "What payment methods do you accept?", a: "We accept UPI, NEFT/IMPS bank transfers, credit/debit cards, and EMI options for select packages. A booking is confirmed only after the advance payment is received." },
  { id: 3, cat: "booking", q: "How much advance do I need to pay to confirm a booking?", a: "Typically 25–30% of the total package cost is required to confirm your booking. The remaining amount is collected 7–10 days before your departure date. For last-minute bookings, full payment may be required upfront." },
  { id: 4, cat: "booking", q: "Is my booking confirmed immediately after payment?", a: "Yes. Once your advance payment is received, we send you a formal booking confirmation with your itinerary, hotel vouchers, transport details, and emergency contact numbers within 24 hours." },
  { id: 5, cat: "booking", q: "Do you offer EMI options for expensive packages?", a: "Yes, EMI options are available for packages above ₹30,000 through select credit cards and BNPL partners. Ask our sales team for the latest options when you enquire." },
  { id: 6, cat: "booking", q: "Is the price fixed or can it change after booking?", a: "Once your booking is confirmed in writing and advance payment received, the package price is locked. Any price changes due to fuel surcharges, hotel rate increases, or tax revisions are communicated before confirmation — never after." },

  // Itinerary & Planning
  { id: 7, cat: "itinerary", q: "Can I customise my itinerary?", a: "Absolutely — in fact, that's our default. Tell us your travel dates, group size, budget, interests (adventure, heritage, leisure, pilgrimage), and any specific places you want to visit. We build the itinerary around you, not the other way around." },
  { id: 8, cat: "itinerary", q: "How far in advance should I book?", a: "We recommend booking at least 15–20 days in advance for domestic trips and 30–45 days for international packages to ensure the best availability and pricing. For peak seasons (December–January, summer, and festive periods), booking 60–90 days ahead is strongly advised." },
  { id: 9, cat: "itinerary", q: "Do you provide hotel recommendations or does the traveller choose?", a: "We provide hotel recommendations across budget, standard, and premium tiers based on your preferences. You can choose from our curated list or request alternatives. All our partner hotels are verified by our team." },
  { id: 10, cat: "itinerary", q: "What is included in a typical package?", a: "A standard package includes accommodation, meals as per the itinerary (CP/MAP/AP basis), transfers (airport/railway to hotel and all sightseeing), a guide where applicable, and emergency support. Flights and personal expenses are typically excluded unless specifically mentioned." },
  { id: 11, cat: "itinerary", q: "Can you add activities or experiences to my itinerary?", a: "Yes. We can arrange adventure activities (trekking, white water rafting, paragliding), cultural experiences, cooking classes, wildlife safaris, and more. Let us know your interests and we'll incorporate them." },
  { id: 12, cat: "itinerary", q: "Do you provide a guide at every destination?", a: "Local guides are included for destinations where they add significant value (heritage cities, wildlife reserves, pilgrimage sites). For leisure beach or hill station trips, a dedicated guide may not be necessary — but our support team is always reachable." },

  // Travel & Logistics
  { id: 13, cat: "travel", q: "Are flights/trains included in your packages?", a: "By default, most packages cover ground transfers only. We can assist with flight or train bookings as an add-on and recommend the best routes. The final package quote will clearly specify what's included." },
  { id: 14, cat: "travel", q: "What type of vehicles do you use for transfers?", a: "We use well-maintained, air-conditioned vehicles appropriate for the terrain — hatchbacks or sedans for flat routes, SUVs and Innova Crystas for mountain routes (Himachal, Ladakh, Uttarakhand). All vehicles are operated by experienced local drivers." },
  { id: 15, cat: "travel", q: "What happens if my flight is delayed and I miss the pick-up?", a: "Inform us as soon as you know about the delay. Our operations team will reschedule your pick-up at no extra charge. We monitor your flight and proactively adjust logistics wherever possible." },
  { id: 16, cat: "travel", q: "Do you arrange airport or railway station pick-up and drop?", a: "Yes. Airport and railway station transfers are included in most packages. Share your arrival and departure details at the time of booking and everything will be pre-arranged." },
  { id: 17, cat: "travel", q: "What should I pack for a hill station or mountain trip?", a: "Layered clothing is key for hill stations. Carry thermal innerwear, a good windcheater or down jacket, sturdy walking shoes, sunscreen, sunglasses, and a first-aid kit. For high-altitude destinations (Ladakh, Spiti), acclimatisation medication is recommended — consult your doctor beforehand." },
  { id: 18, cat: "travel", q: "Is connectivity available at all destinations?", a: "Major destinations have good mobile connectivity. Remote areas like Spiti Valley, some parts of Ladakh, and deep forest regions may have limited or no network. We brief you in advance about connectivity and recommend offline maps and downloaded content." },

  // Safety & Support
  { id: 19, cat: "safety", q: "What happens in a travel emergency?", a: "Our operations team is reachable 24/7. Every traveller receives an emergency contact number before departure. In the event of a medical emergency, vehicle breakdown, or natural disruption, we coordinate alternative arrangements and keep you informed at every step." },
  { id: 20, cat: "safety", q: "Is travel insurance included?", a: "Travel insurance is not included by default but is strongly recommended. We can help you purchase a suitable policy. For international packages, travel insurance covering medical emergencies and trip cancellation is mandatory." },
  { id: 21, cat: "safety", q: "Are your partner hotels safe and verified?", a: "Yes. Every hotel in our network has been physically inspected or verified by our team. We only work with properties that meet our minimum standards for cleanliness, safety, and location. If a property doesn't meet the mark on arrival, we arrange an alternative at no cost to you." },
  { id: 22, cat: "safety", q: "Is it safe to travel solo with Dreams Yatri?", a: "Yes. We have extensive experience with solo travellers, including solo female travellers. Our team checks in daily, your transfers and stays are all confirmed in advance, and you always have a direct line to our support team throughout your trip." },
  { id: 23, cat: "safety", q: "Do you share our personal and payment data?", a: "No. Your data is used solely for trip planning and coordination. We do not share personal or payment information with third parties. Our systems comply with standard data protection practices." },

  // Groups & Families
  { id: 24, cat: "group", q: "Do you handle group bookings?", a: "Yes. We specialise in group travel — corporate offsites, school/college trips, wedding groups, and family reunions. Groups of 10+ get dedicated account management and preferential pricing." },
  { id: 25, cat: "group", q: "Can you accommodate senior citizens or travellers with mobility needs?", a: "Absolutely. We plan trips keeping physical comfort and medical needs in mind. Slower pace, ground-floor rooms, accessible transport, and medical proximity are all factors we factor in. Just share requirements at enquiry stage." },
  { id: 26, cat: "group", q: "Can you plan a family trip with young children?", a: "Yes — family trips are one of our most booked categories. We choose child-friendly hotels, activities suitable for different age groups, and ensure meal flexibility. We also advise on the best destinations for families with specific age groups." },
  { id: 27, cat: "group", q: "Do you organise honeymoon packages?", a: "Yes. Our honeymoon packages are designed for privacy, romance, and surprise moments — candlelight setups, scenic room upgrades, shikara rides, and curated experiences. Share your vision and we'll bring it to life." },
  { id: 28, cat: "group", q: "Can you handle corporate team outings or offsites?", a: "Yes. We handle corporate travel end-to-end — from destination scouting and hotel negotiation to team activity planning and logistics. We've organised offsites for teams ranging from 15 to 200+ people." },

  // Cancellations & Refunds
  { id: 29, cat: "cancellation", q: "What is your cancellation policy?", a: "Cancellation charges depend on how far in advance you cancel: 30+ days before travel — 10% deduction; 15–29 days — 25% deduction; 7–14 days — 50% deduction; less than 7 days — 75–100% deduction. Specific terms are mentioned in your booking confirmation." },
  { id: 30, cat: "cancellation", q: "How do I request a cancellation or modification?", a: "Contact us via email at support@dreamsyatri.com or call +91 70239 07099. All cancellations and modifications must be confirmed in writing. Verbal requests are not processed." },
  { id: 31, cat: "cancellation", q: "How long does a refund take?", a: "Refunds are processed within 7–10 business days after cancellation confirmation. The amount is returned to the original payment source. Bank transfer refunds may take an additional 2–3 business days to reflect." },
  { id: 32, cat: "cancellation", q: "What if the trip is cancelled due to a natural disaster or government advisory?", a: "In cases of force majeure — natural disasters, political unrest, government travel bans — we offer full rescheduling at no charge, or a refund minus actual non-recoverable costs (hotel deposits, activity pre-payments). We always try to protect your money." },
  { id: 33, cat: "cancellation", q: "Can I reschedule my trip to a different date?", a: "Yes, rescheduling is allowed subject to availability and supplier terms. If rescheduled more than 15 days before travel, there is typically no rescheduling fee. Last-minute rescheduling may incur a fee — speak to our team for your specific case." },

  // International Trips
  { id: 34, cat: "international", q: "Do you assist with visa applications?", a: "Yes. For international packages, we provide complete visa guidance — document checklist, application form support, and tracking. For UAE (Dubai) and Thailand, we assist with visa-on-arrival or e-visa applications. Visa fee is not included in the package cost." },
  { id: 35, cat: "international", q: "Which international destinations do you cover?", a: "Currently we offer packages for Dubai, Thailand (Bangkok, Phuket, Krabi), Southeast Asia (Singapore, Bali, Vietnam), and select European destinations. We are actively expanding our international portfolio." },
  { id: 36, cat: "international", q: "Is travel insurance mandatory for international trips?", a: "Yes, travel insurance covering medical emergencies, trip cancellation, and baggage loss is mandatory for all international packages. We can help you purchase a suitable policy." },
  { id: 37, cat: "international", q: "What currency should I carry for international trips?", a: "We advise carrying USD or Euro as a base currency, along with the local currency of your destination. We provide a currency and spending guide as part of your pre-departure briefing. We also recommend a multi-currency forex card." },
  { id: 38, cat: "international", q: "Will there be a language barrier at international destinations?", a: "At major tourist destinations like Dubai, Bangkok, Singapore, and Bali, English is widely spoken in hotels, restaurants, and tourist areas. Our partners at each destination are local and can assist in your language if needed." },

  // General
  { id: 39, cat: "general", q: "Where is Dreams Yatri based?", a: "We are headquartered in Shimla, Himachal Pradesh. Our local roots give us deep expertise in mountain travel across HP, Uttarakhand, and Kashmir — and our growing team covers all major Indian and select international destinations." },
  { id: 40, cat: "general", q: "How is Dreams Yatri different from booking on my own?", a: "When you book independently, you carry the entire logistics burden — hotel confirmations, transport coordination, backup plans, emergency contacts. We absorb all of that. You travel; we manage everything else. Our vendor network also gets you better rates and quality than most direct bookings." },
  { id: 41, cat: "general", q: "Do you have physical offices I can visit?", a: "Our primary office is in Shimla, Himachal Pradesh. While most of our consultations happen via phone and video call, you're welcome to visit in person. Call ahead to schedule an appointment." },
  { id: 42, cat: "general", q: "Can I speak to a real person before booking?", a: "Always. We don't do bots. Call +91 70239 07023 (Mon–Sat, 9 AM–7 PM) or WhatsApp us and a real travel expert will pick up. No automated menus, no hold music." },
  { id: 43, cat: "general", q: "Do you work with travel agents or only direct customers?", a: "We work with both. If you're a travel agent looking to partner with us for packages, reach out to our business development team at sales@dreamsyatri.com. We offer competitive B2B rates and dedicated account support." },
];